[0m17:39:18.763543 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017C094C9820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017C09C8FC80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017C0982C260>]}


============================== 17:39:18.763543 | da2b18b3-fe20-4a47-ad2a-69be1233425f ==============================
[0m17:39:18.763543 [info ] [MainThread]: Running with dbt=1.10.7
[0m17:39:18.763543 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\nekka\\Documents\\netflixdbt\\%userprofile%\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m17:39:18.763543 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\nekka\Documents\netflixdbt\%userprofile%\.dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:39:18.780073 [debug] [MainThread]: Command `dbt run` failed at 17:39:18.778955 after 0.27 seconds
[0m17:39:18.780073 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017C09B8D700>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017C0916AB70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017C09169760>]}
[0m17:39:18.780073 [debug] [MainThread]: Flushing usage events
[0m17:39:19.162988 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:40:45.751975 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020766F9C950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002076A20A7B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002076A5B3E30>]}


============================== 17:40:45.751975 | a1d412f9-a1db-4af1-b7c9-5ba89fd71f9c ==============================
[0m17:40:45.751975 [info ] [MainThread]: Running with dbt=1.10.7
[0m17:40:45.751975 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\nekka\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt run', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:40:45.751975 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\nekka\Documents\netflixdbt\%userprofile%\.dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:40:45.751975 [debug] [MainThread]: Command `dbt run` failed at 17:40:45.751975 after 0.27 seconds
[0m17:40:45.751975 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020766F9C950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002076A6A7C80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002076A634530>]}
[0m17:40:45.751975 [debug] [MainThread]: Flushing usage events
[0m17:40:46.116211 [debug] [MainThread]: An error was encountered while trying to flush usage events
